[package]
name = "rss"
version = "0.4.0"
authors = ["James Hurst <jh.jameshurst@gmail.com>", "Corey Farwell <coreyf@rwell.org>"]
description = "Library for serializing the RSS web content syndication format"
repository = "https://github.com/rust-syndication/rss"
documentation = "https://rust-syndication.github.io/rss/rss/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["rss", "feed", "parser", "parsing"]
include = ["src/*", "Cargo.toml", "LICENSE-MIT", "LICENSE-APACHE", "README.md"]

[dependencies]
quick-xml = "0.4"
